# version: '3.7'

# services:
#   app:
#     build:
#       context: . 
#       dockerfile: docker/deploy/Dockerfile
#     restart: unless-stopped
#     depends_on:
#       - mysql
#     ports:
#       - 3000:3000

#   mysql:
#     image: mysql:5.7
#     # platform: linux/amd64
#     restart: unless-stopped
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: database
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#     ports:
#       - 3306:3306
#     volumes:
#       - "./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql"

version: "3.9"
services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file:
      - .env.postgres
    logging:
      driver: none